dremio/dremio-diagnostic-collector

cli/cli.go, cmd/local/conf/conf.go, cmd/local/conf/job_profile_calculations.go, cmd/local/conf/job_profile_calculations_test.go
- job profile calculations were totally wrong
- fixed another race, fixed job profile calculations with no pat token
=> 23 validate job profile calculations for distribution

CHANGELOG.md, cmd/root/collection/capture.go, cmd/root/collection/capture_test.go, cmd/root/ssh/ssh.go, cmd/root/ssh/ssh_test.go, integrationtest/ssh/collect_ssh_test.go
Final changes for ssh banner etc
=> 102 ssh banner can break scp transfer back to local nodes

cmd/root/cli/cli.go, cmd/root/cli/cli_test.go, cmd/root/collection/capture.go, cmd/root/collection/capture_test.go, cmd/root/collection/cluster.go, cmd/root/collection/collector.go, cmd/root/collection/collector_test.go, cmd/root/collection/sudo.go, cmd/root/collection/sudo_test.go, cmd/root/kubernetes/kubernetes.go, cmd/root/kubernetes/kubernetes_test.go, cmd/root/ssh/ssh.go, cmd/root/ssh/ssh_test.go, pkg/masking/config_mask.go, pkg/masking/config_mask_test.go, pkg/tests/mocks.go
Changed to add additional flag to pass around - then masking the log output in cli.go
=> 116 dremio pat is being logged in ddclog

cmd/root.go, cmd/root/collection/collector.go, cmd/root/kubernetes/kubernetes.go, cmd/root/kubernetes/kubernetes_test.go, integrationtest/kube/collect_kube_test.go
Made updates, ran tests with relevant changes and successfully ran cibuild
=> 115 scale out coordinator collection problem seen with unknown container

cmd/local/conf/conf.go, cmd/local/conf/conf_test.go
Removes the problems we can get with trailing slash requests to certain APIs.
=> Added check for trailing slash

cmd/root/helpers/fshelper.go
Quick fix to resolve failing build
=> efix for PR123

CHANGELOG.md, cmd/local/jvmcollect/jfr.go
- adding quiet stop of jfr
- updated changelog with jfr fix
=> fix ssh test

CHANGELOG.md, cmd/awselogs/awselogs.go, cmd/local/conf/conf.go, cmd/local/local.go, cmd/root.go, pkg/simplelog/logger.go, pkg/simplelog/logger_test.go
- logging file start and stop
- better logging message
- fallback logging
=> 138 have ddclog fall back to the tmp directory if its current location is not writeable

CHANGELOG.md, cmd/local/jvmcollect/jfr.go, cmd/local/jvmcollect/jfr_test.go
- cleaner jfr stop message
- log now only when a record is actually stopped
=> 147 remove log for jfr stop

cmd/root.go, cmd/root/collection/collector.go, cmd/root/collection/summary.go, cmd/root_test.go, pkg/consoleprint/consoleprint.go
So this just adds the following things
* collection tasks that will run
* collection tasks that are disbabled (either by default, by config, or because the pat was forgotten)
* adds a big giant front and center message that the pat was forgotten, what that disables and how to fix this if you don't like that
* adds some useful things to the summary.json just because
=> added more information to the TUI to make clear the collection status

CHANGELOG.md, cmd/root.go, cmd/root/collection/collector.go, cmd/root/helpers/healthcheck_strategy.go, cmd/root/helpers/healthcheck_strategy_test.go, pkg/archive/archive.go, pkg/archive/archive_test.go
- health check cleanup is now explicit and no longer deletes whole temp folder
- no longer create a temp dir in /tmp to copy transferred files too for
ddc but instead use the output directory of the diag tarball
- no longer find all tarballs in ddc destination directory but track
tarballs that have been copied and then untar and delete those
- now only archive the summary.json and the created ddc output dir in
the ddc destination dir
=> health check strategy cleanup

README.md
reformatted and clarified README doc
=> reformatted and clarified README doc

CHANGELOG.md, cmd/local/conf/conf.go, cmd/local/conf/conf_key_names.go, cmd/local/conf/defaults.go, cmd/local/local.go, cmd/root.go, cmd/root/collection/capture.go, cmd/root/collection/collector.go, go.mod, pkg/dirs/dirs.go, pkg/dirs/free_space_posix.go, pkg/dirs/free_space_posix_test.go, pkg/dirs/free_space_win.go, pkg/dirs/free_space_win_test.go
I have not validated the windows code yet, but will get that loaded this afternoon..wanted to get this back into master before it spent too much time outside of it
--disable-free-space-check available on local-collect and default ddc command to override this
=> free space detection

cmd/local/local.go, cmd/root.go, cmd/root/collection/collector.go
* local-collect --pid for automation
* --transfer-threads hidden flag for advanced users
=> added local-collect pid and transfer-threads flag

CHANGELOG.md, cmd/root/collection/capture.go, cmd/root/kubernetes/kubernetes.go, pkg/consoleprint/consoleprint.go
- **poc on reduced status list**
- **cleaned output**
- **changelog bump**
=> short status list

CHANGELOG.md, cmd/root/kubernetes/kubernetes.go, pkg/archive/archive.go
- **fixed hang on copy to pod**
- **added retries**
- **ready changelog**
=> k8s api retries

CHANGELOG.md, cmd/local/queriesjson/queries.go, cmd/root.go, cmd/root/collection/capture.go, cmd/root/kubernetes/kubernetes.go
- **fixed a race, bumped retry to 50 times**
- **more consistent logging**
=> race in buffer output

CHANGELOG.md, cmd/local/conf/defaults.go, cmd/local/conf/defaults_test.go, cmd/root.go, cmd/root/kubernetes/kubernetes.go, default-ddc.yaml, kubernetes/role-binding.yaml, pkg/consoleprint/consoleprint.go
- **prommpt ui fixes, labels in k8s again, defaults**
- **Support filtering k8s pods by label selector**
=> detect namespace should skip prompt

CHANGELOG.md, cmd/root.go, cmd/root/kubernetes/kubernetes.go
Lowering timeout for transfer to 30 minutes intead of 60 minutes to make failure less time consuming
=> failing hung transfers faster

CHANGELOG.md, cmd/root/collection/capture.go, cmd/root/collection/collector.go, cmd/root/kubectl/kubectl.go, cmd/root/kubernetes/kubernetes.go, cmd/root/ssh/ssh.go, pkg/archive/archive.go, pkg/shutdown/shutdown.go, script/build-musl, script/release-build-musl, script/release-musl
* enhanced output of cleanup tasks in UI
* Windows installs without kubectl now function correctly
* Cleanup tasks were slower than they needed to be. Large speedup on large clusters.
* removed hook from StartCapture
=> k8s api on windows, cleanup, ui fixes

CHANGELOG.md, cmd/root.go, cmd/root/collection/collector.go, pkg/shutdown/shutdown.go
- **shutdown no longer stops already stopped processes**
- **changelog bumpb**
=> improve shutdown

cmd/local/local.go
Added the extra line into os-info.txt - its a trivial change so I didn't add a test - but lmk if we really need that
=> Adding stat for cgroups

CHANGELOG.md, cmd/local/local.go
* cleaned up the cgroupsv2 output
* output memory, cpu, and io pressure container status
* get load avg stats from the proc filesystem
=> adding cgroupsv2 pressure stats

CHANGELOG.md, cmd/root/collection/collector.go, cmd/root/fallback/fallback.go, cmd/root/kubectl/kubectl.go, cmd/root/kubernetes/kubernetes.go, cmd/root/ssh/ssh.go
* added collection of nat container log via kubectl and kube api
=> added support for nats logs

CHANGELOG.md, cmd/root.go, cmd/root/collection/cluster.go, cmd/root/collection/collector.go, cmd/root/fallback/fallback.go, cmd/root/kubectl/kubectl.go, cmd/root/kubectl/kubectl_test.go, cmd/root/kubernetes/kubernetes.go, cmd/root/ssh/ssh.go, integrationtest/kube/collect_kube_test.go
- all pod log collection
- adding retries count for kubectl
- removed zookeeper specific code for log capture
=> generic container log collection
