- cmd/local/apicollect/jobprofiles.go
- cmd/local/conf/conf.go
- cmd/local/conf/conf_test.go
- cmd/local/conf/job_profile_calculations.go
- cmd/local/queriesjson/queries.go
- collection/collector.go
- default-ddc.yaml
* coordinator pods were not collecting REST calls ever
* job profile calculation had extra uncessary test for pat check
* updated commentary in ddc.yaml for job profiles to explain it is "up
to" instead of "it will be" this number of job profiles
* we were needlessly returning a map in Add queriesjson.AddRowsToSet
* dremio PAT is no longer logged in the logs and it is now REDACTED when
present, however an empty PAT is logged for debugging purposes
> job profile collection fixes and masking pat

- cmd/local/apicollect/jobprofiles.go
- cmd/local/apicollect/kvreports.go
- cmd/local/apicollect/system_tables.go
- cmd/local/apicollect/validate.go
- cmd/local/apicollect/wlm.go
- cmd/local/conf/conf.go
- cmd/local/conf/parse_config.go
- cmd/local/local.go
- cmd/local/logcollect/logcollect.go
- cmd/local/queriesjson/queries.go
- cmd/local/threading/thread_pool.go
- cmd/local/threading/thread_test.go
- cmd/root/cli/cli.go
- cmd/root/collection/capture.go
- cmd/root/collection/collector.go
- main.go
- pkg/masking/config_mask.go
- pkg/simplelog/logger.go
* We have normalized interpretation of the --dremio-pat-token parameter
when passed to executors across ssh and kubernetes, both interpret a
blank argument differently ssh views `--dremio-pat-token ` as no
argument for --dremio-pat-token and kubernetes exec views that as an
empty argument. Likewise if one provides `--dremio-pat-token ""` ssh
will see that as en empty argument and kubernetes will escape the
quotes sending "\"\"" as the argument for --dremio-pat-token. This has
all been normalized and the values "" and "\"\"" are considered
equivalent when parsing command line args in local-collect
* Reduced console logging considerable and default verbosity level, each
nodes ddc.log however is still maximum verbosity
* logging was not cleaning dropping older configuration, now it does
* …
> Executors were not running capture on ssh

- cmd/root.go
- cmd/root/helpers/fshelper.go
- cmd/root/helpers/healthcheck_strategy.go
- cmd/root/helpers/healthcheck_strategy_test.go
Ensures we use the configured tmp path before defaulting to the OS tmpdir. Add missing error check
> 123 unexpected use of tmp path

- cmd/local/local.go
- cmd/root.go
- cmd/root/collection/cluster.go
- cmd/root/helpers/healthcheck_strategy.go
- integrationtest/kube/collect_kube_test.go
Two commits here: 
- fixes an issue where we send incorrect jcmd syntax and we only got an exit code 1
- adds collection of kubectl describe nodes
> 165 include kubectl describe node as text output in ddc

- integrationtest/kube/collect_kube_test.go
- pkg/tests/file.go
- pkg/tests/file_test.go
The test was failing because we were counting up the matches and if we had multiple matches of one thing then the count would be > expected. While this is ok, we need to make sure we have one match on each string and not 10 on one and none on the other so it needed a bit more thought
> Fix failing test

- CHANGELOG.md
- cmd/local/conf/conf.go
- cmd/local/conf/defaults.go
- cmd/local/conf/defaults_test.go
- cmd/root.go
- cmd/root/collection/capture.go
main thing this provides is largely making tmp-output-dir obsolete and I've set the stage for it to be deprecated and removed. This will make later documentation much easier to understand and this will now become easier to avoid the tmp folder just by setting one parameter
> tmp-output-dir now defaults to tarball-out-dir

- cmd/root/collection/collector.go
This is part of the temp fix and fits in with the pattern we are using where the tarball output folder is where we have decided to start doing file work in ddc. While this is suboptimal from a folder content perspective and makes the intermediary status of folder creation visible to the end user it does mean cleanup is more trivial and obvious, if not as automatic as when we use the temp folder
> avoiding use of tmp for transfer of ddc binary and yaml

- cmd/local/apicollect/jobprofiles_test.go
- cmd/local/apicollect/wlm_test.go
- cmd/local/conf/conf.go
- cmd/local/conf/conf_test.go
- cmd/local/configcollect/dremio_conf_test.go
- cmd/local/jvmcollect/heap_dump_test.go
- cmd/local/jvmcollect/jfr_test.go
- cmd/local/jvmcollect/jstack_test.go
- cmd/local/jvmcollect/jvm_flags_test.go
- cmd/local/local.go
- cmd/local/local_test.go
- integrationtest/ssh/collect_ssh_test.go
* validation for the local-collect command was in a weird place leading to lots of state issues in tests. now it will happen strictly in the initial cli parsing where there are less moving parts
> Move validation

- CHANGELOG.md
- cmd/local/conf/defaults.go
- cmd/local/conf/defaults_test.go
- cmd/local/local.go
- default-ddc.yaml
* when doing light and health check and the pat is added will collect 20
profiles
* moved rest collection except job profiles to front of collection to
avoid bearer token expiration at the end of the job
> better job profile collection defaults

- CHANGELOG.md
- pkg/dirs/dirs.go
- **removed log message for free space when there is adequate free space**
- **removed confusing free space log**
> ddc free space check fix

- CHANGELOG.md
- cmd/root.go
- cmd/root/collection/cluster.go
- cmd/root/kubectl/kubectl.go
- cmd/root/kubectl/kubectl_test.go
- cmd/root/kubernetes/kubernetes.go
- pkg/consoleprint/consoleprint.go
Reduced the number of connections to k8s..that was excessive prior, and now I log the context used
Also now log the output of the current context if none is set and display this in the UI to make it more obvoius which one is in use
> support for custom kubernetes context with ddc

- CHANGELOG.md
- cmd/local/local.go
- cmd/local/local_test.go
- cmd/root/ssh/ssh.go
* cluster id collection now longer searches the rocksdb folders and no
longer depends on it being correctly configured
* ssh copy no longer transfers to the same file name
> cluster id collect speedup, improve ssh copy

- CHANGELOG.md
- cmd/root.go
- cmd/root/kubectl/kubectl.go
- cmd/root/kubectl/kubectl_test.go
- kubectl strategy had hard-coded the default role of role=dremio-cluster-pod, this is now fixed and uses the same kubectl args that is used by the kubernetes api strategy fixes #280
> fix custom label for kubectl strategy

- CHANGELOG.md
- cmd/local/apicollect/system_tables.go
- cmd/local/apicollect/system_tables_test.go
- cmd/local/conf/conf.go
- cmd/local/conf/conf_key_names.go
- cmd/local/conf/defaults.go
- cmd/local/conf/defaults_test.go
- default-ddc.yaml
During some health checks although system tables are needed there may be a need to exclude some system tables, in particular jobs_recent as it can be quite large
This change adds the following parameter into the `ddc.yaml` for example
```
skip-system-table: jobs,jobs_recent # csv list of system tables to skip
```
allows you to include a list of tables you might want to skip
> Parameterize systables

- README.md
- cmd/local/apicollect/jobprofiles.go
- cmd/local/conf/conf.go
- cmd/local/conf/conf_key_names.go
- cmd/local/conf/conf_test.go
- cmd/local/conf/defaults.go
- cmd/local/conf/defaults_test.go
- cmd/local/local.go
- cmd/testdata/ddc-valid.yaml
- default-ddc.yaml
added "is-rest-collect" mode to allow DDC via REST API only (similar to "is-dremio-cloud" collect mode, but for Dremio Software).
This mode can be run as "local-collect" and will collect the following via REST:
- System tables (incl. sys.jobs_recent)
- Job Profiles
- WLM
- KV store report
> added "is-rest-collect" mode to allow DDC via REST API only

- README.md
- cmd/local/apicollect/system_tables.go
- cmd/local/apicollect/system_tables_test.go
- cmd/local/apicollect/wlm.go
- cmd/local/conf/conf.go
- cmd/local/conf/conf_key_names.go
- cmd/local/conf/defaults.go
- cmd/local/local.go
- cmd/testdata/ddc-valid.yaml
- cmd/testdata/queries/cluster_usage.json
- default-ddc.yaml
- removed sys.jobs_recent from default DDC
- For REST-only DDC, added guardrail for collecting sys.jobs_recent only for small and medium-sized clusters based via "rest-collect-daily-jobs-limit"
- Limited sys.jobs_recent collection to 7 days max
> introduced selective collection of sys.jobs_recent based on collection mode and cluster size

- CHANGELOG.md
- cmd/local/conf/conf.go
fixed an issue where the log directory was not being detected correctly if queries.json was the only log type being collected
> fixed an issue where the log directory was not being detected correctly if queries.json was the only log type being collected

- CHANGELOG.md
- cmd/local/conf/conf_test.go
- cmd/local/ddcio/ddcio_test.go
- cmd/local/jvmcollect/jfr_test.go
- cmd/root.go
- cmd/root_test.go
- main.go
- pkg/archive/archive.go
- pkg/archive/archive_test.go
- pkg/simplelog/logger.go
- pkg/simplelog/logger_test.go
Also added some more tests, manually tested with:
- set `--output-file`to a diff location from when `CWD` and checked that the archive includes it 
- didnt set `--output-file` and it runs ok
The only thing that can happen is a empty `ddc.log` is created in the `CWD` when the `init` is run during normal usage - I dont see this as a problem though?
> Changes to fix #308

- cmd/local/local.go
- cmd/root.go
- cmd/root/collection/capture.go
- cmd/root/collection/collector.go
- -z this allows us to control throttling rates for kubectl cp effectively by controlling chunk size
- -a disables this behavior and returns to the old approach
> added -z and -a flag to root command

- CHANGELOG.md
- cmd/local/conf/conf.go
- cmd/local/logcollect/logcollect.go
- pkg/dirs/dirs.go
- to help in debugging we are adding the file copy paths
- we log more detail around which configuration directory is used and which log directory is used as well as more thorough explanations for the reasoning behind the choice made
> extra logging for file moving
